[project]
name = "music-visualizations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lyricsgenius>=3.2.0",
    "plotly>=5.24.1",
    "scikit-learn>=1.6.0",
    "spotipy>=2.24.0",
    "streamlit>=1.40.1",
]
